# dataset_long.csv, dataset_wide.csv를 youtube_channels_filtered.csv기준으로 filter하는 노트북입니다.

In [1]:
import pandas as pd

In [2]:
dataset_long = pd.read_csv("data/raw/dataset_long.csv")
dataset_wide = pd.read_csv("data/raw/dataset_wide.csv")
youtube_channels_filtered = pd.read_csv("data/raw/youtube_channels_filtered.csv")

/var/folders/fd/8k73lf_11pjfmg3f69043_q00000gn/T/ipykernel_97643/389617135.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset_long = pd.read_csv("data/raw/dataset_long.csv")

In [5]:
# channel_id 기준으로 dataset_long 필터링

filtered_dataset_long = dataset_long[

    dataset_long["channel_id"].isin(

        youtube_channels_filtered["youtube_channel_id"]

    )

]
filtered_dataset_long.head()

,idx,channel_id,channel_title,video_id,video_title,published_at,duration_sec,is_shorts,view_count,like_count,comment_count,source_file,title,channel_created_at,country,subscriber_count,channel_total_views,total_video_count
139020,3270,UC0kp1x32b-Y4cvP5r3vW_hw,Sereno Official,yOTYf7a8XBY,Sereno - 목설화 (目雪話),2017-09-21 11:07:10+00:00,195.0,False,314804.0,2497.0,84.0,videos_3250-3299.csv,Sereno Official,2015-11-02T10:38:22Z,KR,100000.0,46972796.0,78.0
139021,3270,UC0kp1x32b-Y4cvP5r3vW_hw,Sereno Official,3FukdocUxrI,Sereno - 한밤중의 별빛찬가,2017-09-22 10:30:00+00:00,157.0,False,697303.0,5907.0,268.0,videos_3250-3299.csv,Sereno Official,2015-11-02T10:38:22Z,KR,100000.0,46972796.0,78.0
139022,3270,UC0kp1x32b-Y4cvP5r3vW_hw,Sereno Official,7bjkQxWQvDI,Sereno - I Will Sleep Hand In Hand,2017-09-25 13:34:37+00:00,209.0,False,316484.0,4271.0,311.0,videos_3250-3299.csv,Sereno Official,2015-11-02T10:38:22Z,KR,100000.0,46972796.0,78.0
139023,3270,UC0kp1x32b-Y4cvP5r3vW_hw,Sereno Official,PfEfcqb5aHw,Sereno - 새벽 별과 소년의 노래 (Piano Solo),2017-09-29 12:43:56+00:00,232.0,False,1364038.0,8563.0,200.0,videos_3250-3299.csv,Sereno Official,2015-11-02T10:38:22Z,KR,100000.0,46972796.0,78.0
139024,3270,UC0kp1x32b-Y4cvP5r3vW_hw,Sereno Official,x_cbMVKDotI,Sereno - 저녁 노을에 감사를,2017-10-20 09:32:49+00:00,186.0,False,332625.0,2610.0,103.0,videos_3250-3299.csv,Sereno Official,2015-11-02T10:38:22Z,KR,100000.0,46972796.0,78.0

In [6]:
# channel_id 기준으로 dataset_wide 필터링

filtered_dataset_wide = dataset_wide[

    dataset_wide["channel_id"].isin(

        youtube_channels_filtered["youtube_channel_id"]

    )

]
filtered_dataset_wide.head()

,channel_id,title,published_at,subscriber_count,view_count,total_video_count,source_file,collected_video_count,days_since_last_upload,avg_upload_interval_days,...,hiatus_count_30d,upload_freq_change_rate,avg_view_count,std_view_count,avg_like_count,avg_comment_count,avg_engagement_rate,shorts_ratio,avg_shorts_view,avg_normal_view
2508,UC0_yHLyKYYvG4bzylDs3pwA,2M (투엠) ENT,2009-03-16T14:52:53Z,100000,10030245,557,channels_must_3250_3299.csv,50.0,2.0,0.96,...,0.0,5.000000e+10,3583.14,8651.12,84.52,2.96,0.035743,0.96,3687.46,1079.50
2512,UCDYdwDXhbVZXkdV6kZn-0IQ,심킹 (ABYSSKIMG),2012-05-01T15:10:54Z,100000,9668787,112,channels_must_3250_3299.csv,50.0,1120.0,22.61,...,5.0,0.000000e+00,55364.56,57049.86,483.32,176.76,0.014234,0.06,1549.67,58799.55
2513,UCbr6AL4ayehAkXcdBM68e8A,김PD전당포,2012-01-06T08:48:32Z,100000,2156709,135,channels_must_3250_3299.csv,50.0,448.0,36.69,...,7.0,0.000000e+00,1516.14,2263.11,34.86,2.16,0.015272,0.32,2111.50,1235.97
2514,UCJQDi71H00IXCQbxAtFem3Q,DC튜브,2015-12-19T23:24:19Z,100000,30385528,2043,channels_must_3250_3299.csv,50.0,14.0,14.12,...,10.0,5.000000e-01,5020.40,4387.90,62.90,21.66,0.019500,0.58,4605.66,5593.14
2515,UCR33sqrqf6rlT2AlpgyKmyA,두리 원투쓰리코,2019-03-12T15:59:11Z,109000,123170488,1630,channels_must_3250_3299.csv,50.0,1.0,0.00,...,0.0,5.000000e+10,20873.78,57756.46,88.86,6.80,0.007655,0.96,21373.56,8879.00

In [8]:
# 저장
filtered_dataset_long.to_csv("filtered_dataset_long.csv", index=False, encoding="utf-8-sig")
print("저장 완료: filtered_dataset_long.csv")

filtered_dataset_wide.to_csv("filtered_dataset_wide.csv", index=False, encoding="utf-8-sig")
print("저장 완료: filtered_dataset_wide.csv")

저장 완료: filtered_dataset_long.csv
저장 완료: filtered_dataset_wide.csv